---
- hosts: db
  vars:
    db_password: password
  tasks:
    - name: first
      copy: src=db/MariaDB.repo dest=/etc/yum.repos.d/MariaDB.repo mode=0644

    - name: second
      become: yes
      yum: name=MariaDB-server,MariaDB-client update_cache=yes state=present

    - name: third
      become: yes
      service: name=mariadb state=started enabled=yes

    - name: fourth
      template: src=db/mariadb_answers.txt dest=/tmp/mariadb_answers.txt mode=0644

    - name: fifth
      become: yes
      shell: /usr/bin/mysql_secure_installation </tmp/mariadb_answers.txt

    - name: sixth
      unarchive: src=db/db.tgz dest=~/

    - name: seventh
      command: ./make_databases.sh {{ db_password }} localhost chdir=~/db
      ignore_errors: True

